# Generated by Django 4.2.4 on 2023-08-31 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortcode',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='URLHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_shortner_api.url')),
            ],
        ),
    ]
